using System;using System.IO;using System.Collections.Generic;using System.Web.Script.Serialization;
class CepSafety {
 static List<string> checks=new List<string>();static void Pass(bool ok,string text){if(!ok)throw new Exception(text);checks.Add(text);Console.WriteLine("PASS "+text);}
 static Dictionary<string,object> Status(CepManager m){var j=new JavaScriptSerializer();return j.Deserialize<Dictionary<string,object>>(j.Serialize(m.Status()));}
 static int Main(string[] args){try{AppContext.SetSwitch("Switch.System.IO.UseLegacyPathHandling",false);AppContext.SetSwitch("Switch.System.IO.BlockLongPaths",false);string root=Path.GetFullPath(args[0]);Directory.CreateDirectory(root);var m=new CepManager(root,true);CepManager.VerifyEmbeddedSetup();m.Apply("install",true,null);string dest=(string)Status(m)["path"],area=Path.Combine(root,"CepSandbox","Adobe","CEP","toolkit-install");
 using(var lease=new FileStream(Path.Combine(area,"install.lock"),FileMode.Open,FileAccess.ReadWrite,FileShare.None)){bool blocked=false;try{m.Apply("uninstall",false,null);}catch(IOException){blocked=true;}Pass(blocked&&Directory.Exists(dest),"External installer lock blocks concurrent uninstall without moving files");}
 m.Apply("uninstall",false,null);var state=Status(m);var backups=(System.Collections.ArrayList)state["backups"];string restore=(string)backups[0];m.Apply("install",true,null);File.WriteAllText(Path.Combine(dest,"marker.txt"),"current installation");File.WriteAllText(Path.Combine(root,"simulate-restore-failure"),"1");bool failed=false;try{m.Apply("restore",true,restore);}catch(IOException){failed=true;}Pass(failed&&File.ReadAllText(Path.Combine(dest,"marker.txt"))=="current installation","Injected restore failure returns the replaced installation intact");File.Delete(Path.Combine(root,"simulate-restore-failure"));m.Apply("repair",true,null);
 File.Delete(Path.Combine(root,"test-cep-debug"));Pass((string)Status(m)["state"]=="Needs repair","Disabled unsigned-panel settings are reported as Needs repair");m.Apply("repair",true,null);Pass((string)Status(m)["state"]=="Installed","Repair restores disabled settings and complete package integrity");
 byte[] valid=Installer.Payload();using(var ms=new MemoryStream()) {using(var z=new System.IO.Compression.ZipArchive(ms,System.IO.Compression.ZipArchiveMode.Create,true)){var e=z.CreateEntry(Installer.Bundle+"/../../escape.txt");using(var w=new StreamWriter(e.Open()))w.Write("blocked");}failed=false;try{Installer.Extract(ms.ToArray(),Path.Combine(root,"traversal"));}catch(IOException){failed=true;}Pass(failed&&!File.Exists(Path.Combine(root,"escape.txt")),"ZIP traversal fails before a file escapes the staging folder");}
 File.WriteAllText(Path.Combine(root,"cep-safety-results.json"),new JavaScriptSerializer().Serialize(new{passed=true,checks=checks}));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}
}
