const fs=require('fs'),path=require('path'),assert=require('assert'),{spawn}=require('child_process');
const {chromium}=require('playwright');
const base=path.resolve(__dirname,'..');const checks=[];function pass(s){checks.push(s);console.log('PASS '+s);}
(async()=>{const profile=base+'/tests/extended-'+Date.now();fs.mkdirSync(profile,{recursive:true});fs.copyFileSync(base+'/build/Toolkit.exe',profile+'/Toolkit.exe');const proc=spawn(profile+'/Toolkit.exe',['--self-test','--profile',profile],{windowsHide:true});let browser;
try{for(let i=0;i<100&&!fs.existsSync(profile+'/server-info.json');i++)await new Promise(r=>setTimeout(r,100));const info=JSON.parse(fs.readFileSync(profile+'/server-info.json')),url=info.url;assert(fs.existsSync(profile+'/App/2.2.0/app.js'));pass('Single EXE extracts its embedded interface without companion files');
browser=await chromium.launch({headless:true,channel:'msedge'});let page=await browser.newPage({viewport:{width:1500,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>window.ToolkitDiagnostics);
const invalid=await page.evaluate(()=>{const p=ToolkitDiagnostics.state().project;let a=[];for(const fn of [p=>p.width=Infinity,p=>p.zones[0].seats[0].x='0',p=>p.zones[0].seats[1].uid=p.zones[0].seats[0].uid,p=>p.stage.d='<script>alert(1)</script>']){const q=Toolkit.clone(p);fn(q);try{Toolkit.checkProject(q);a.push(false);}catch{a.push(true);}}return a;});assert(invalid.every(Boolean));pass('Malformed project dimensions, seat values, duplicate identities and active markup are rejected');
const imported=await page.evaluate(()=>{let a=[];const source=Toolkit.svg(ToolkitDiagnostics.state().project);for(const text of [source.replace('<svg ','<!DOCTYPE svg><svg '),source.replace('</svg>','<script>alert(1)</script></svg>'),source.replace('<rect id="seatData-','<path id="seatData-')]){try{importMapSVG(text);a.push(false);}catch{a.push(true);}}return a;});assert(imported.every(Boolean));pass('Unsafe SVG declarations, active content and unsupported seat geometry fail before changing the project');
await page.click('[data-mode="zones"]');await page.click('#selectStage');const seatsBefore=await page.evaluate(()=>JSON.stringify(ToolkitDiagnostics.state().project.zones));const selects=page.locator('#inspector select');await selects.nth(1).selectOption('hexagon');await page.getByRole('button',{name:'Apply stage shape',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.stringify(ToolkitDiagnostics.state().project.zones)),seatsBefore);pass('Stage can change shape without rebuilding any seats or sections');
const seat=page.locator('#map [data-seat]').first(),bb=await seat.boundingBox(),before=await page.evaluate(()=>ToolkitDiagnostics.state().project.zones[0].seats[0]);await seat.click();await page.keyboard.press('ArrowRight');let after=await page.evaluate(()=>ToolkitDiagnostics.state().project.zones[0].seats[0]);assert.equal(after.x,before.x+1);await page.click('#undo');assert.equal((await page.evaluate(()=>ToolkitDiagnostics.state().project.zones[0].seats[0])).x,before.x);pass('Seat keyboard movement and undo preserve the original coordinates');
await page.locator('.zone-item').first().click();const initial=await page.evaluate(()=>ToolkitDiagnostics.state().project.zones[0]);const bbox=await page.locator('#map .selected-section').boundingBox();const dragPoint=await page.locator('#map .selected-section').evaluate(el=>{const b=el.getBBox(),p=new DOMPoint(b.x+b.width/2,b.y+1).matrixTransform(el.getScreenCTM());return {x:p.x,y:p.y};});await page.mouse.move(dragPoint.x,dragPoint.y);await page.mouse.down();await page.mouse.move(dragPoint.x+25,dragPoint.y+30,{steps:4});await page.mouse.up();let moved=await page.evaluate(()=>ToolkitDiagnostics.state().project.zones[0]);const dx=moved.seats[0].x-initial.seats[0].x,dy=moved.seats[0].y-initial.seats[0].y;assert(Math.abs(dx)>1&&Math.abs(dy)>1);assert(Math.abs((moved.label.x-initial.label.x)-dx)<1e-8);assert(Math.abs((moved.section.bounds[1]-initial.section.bounds[1])-dy)<1e-8);await page.click('#undo');pass('Dragging a zone moves seats, section and label together; Undo restores it');
await page.click('[data-mode="history"]');await page.fill('#snapshotName','Original');await page.click('#snapshot');await page.fill('#projectName','Recovery test');await page.locator('#projectName').press('Tab');await page.locator('.snapshot-card').getByRole('button',{name:'Restore',exact:true}).click();await page.click('#dialogOK');assert.equal(await page.locator('#projectName').inputValue(),'Untitled venue');await page.fill('#projectName','Recovered session');await page.locator('#projectName').press('Tab');await page.waitForTimeout(1300);const saved=JSON.parse(fs.readFileSync(profile+'/Recovery.venue','utf8'));assert.equal(saved.project.name,'Recovered session');
await page.close({runBeforeUnload:false});page=await browser.newPage({viewport:{width:1500,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForSelector('#dialog[open]');await page.click('#dialogOK');assert.equal(await page.locator('#projectName').inputValue(),'Recovered session');assert.equal((await page.evaluate(()=>ToolkitDiagnostics.state())).snapshots.length,1);pass('Snapshot restore and full session recovery retain saved project data');
await page.fill('#zones','4');await page.fill('#seats','5000');await page.fill('#rows','100');const started=Date.now();await page.click('#previewBuild');await page.waitForFunction(()=>document.querySelectorAll('#map .seat').length===20000);const ms=Date.now()-started;await page.click('#cancelBuild');assert.equal(await page.locator('#map .seat').count(),576);pass('20,000-seat preview renders in '+ms+' ms and cancels without replacing the current map');
const imageTest=await page.evaluate(async()=>{const worker=new Worker('trace-worker.js');const w=24,h=24,pixels=new Uint8ClampedArray(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const n=(y*w+x)*4;pixels.set((x+y)%3===0?[20,50,90,255]:[170,60,20,255],n);}const data=await new Promise((resolve,reject)=>{worker.onmessage=e=>{if(e.data.result)resolve(e.data.result);if(e.data.error)reject(Error(e.data.error));};worker.postMessage({pixels:pixels.buffer,width:w,height:h,colors:2,removeWhite:false,minArea:0});});worker.terminate();const svg='<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24">'+data.paths.map(p=>'<path d="'+p.d+'" fill="'+p.fill+'" fill-rule="evenodd"/>').join('')+'</svg>';const img=new Image();img.src='data:image/svg+xml;base64,'+btoa(svg);await img.decode();const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0);const actual=c.getContext('2d').getImageData(0,0,w,h).data;return pixels.every((v,i)=>v===actual[i]);});assert(imageTest);pass('Two-colour diagonal contours rasterize back to the exact source pixels');
assert.deepEqual(errors,[]);await page.click('[data-mode="build"]');await page.fill('#projectName','Grand Hall');await page.locator('#projectName').press('Tab');await page.selectOption('#layout','amphitheatre');await page.selectOption('#stageType','rounded');await page.fill('#zones','4');await page.fill('#seats','192');await page.fill('#rows','12');await page.click('#previewBuild');await page.click('#applyBuild');await page.click('#dialogOK');await page.waitForTimeout(5600);await page.screenshot({path:base+'/tests/Preview.png'});
}finally{if(browser)await browser.close();proc.kill();}fs.writeFileSync(base+'/tests/extended-results.json',JSON.stringify({passed:true,checks},null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
