const fs=require('fs'),path=require('path'),assert=require('assert'),{spawn}=require('child_process');
const {chromium}=require('playwright');
const JSZip=require('jszip');
const acorn=require('acorn');
const base=path.resolve(__dirname,'..'),checks=[];function pass(s){checks.push(s);console.log('PASS '+s);}
(async()=>{const profile=base+'/tests/extra-'+Date.now();fs.mkdirSync(profile,{recursive:true});const proc=spawn(base+'/build/Toolkit.exe',['--self-test','--profile',profile],{windowsHide:true});let browser;
try{for(let i=0;i<100&&!fs.existsSync(profile+'/server-info.json');i++)await new Promise(r=>setTimeout(r,100));const info=JSON.parse(fs.readFileSync(profile+'/server-info.json'));browser=await chromium.launch({headless:true,channel:'msedge'});let page=await browser.newPage({viewport:{width:1500,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(info.url);await page.click('#productionOpen');await page.waitForFunction(()=>document.getElementById('productionFrame').contentWindow.ProductionBridge?.state().seats===576);let frame=page.frames().find(f=>f.url().includes('production.html'));await frame.waitForTimeout(700);
const before=await frame.evaluate(()=>[...STATE.svg.querySelectorAll('[id^="seatData-"]')].map(s=>({id:s.id,x:s.getAttribute('x'),y:s.getAttribute('y')})));
await frame.locator('[data-tab="studio"]').click();await frame.click('#repairSafeBtn');await frame.waitForTimeout(300);assert.deepEqual(await frame.evaluate(()=>[...STATE.svg.querySelectorAll('[id^="seatData-"]')].map(s=>({id:s.id,x:s.getAttribute('x'),y:s.getAttribute('y')}))),before);assert.equal(await frame.evaluate(()=>verifyV6Baseline()),true);await frame.click('#undoBtn');assert.equal(await frame.evaluate(()=>countSeats()),576);pass('Transactional safe repair and Undo preserve all original seat IDs and coordinates');
await frame.locator('[data-tab="artwork"]').click();await frame.setInputFiles('#artFileInput',base+'/tests/fixtures/Artwork.png');await frame.waitForFunction(()=>STATE.artworkSource!==null);await frame.click('#artGenerateBtn');await frame.waitForTimeout(300);for(let i=0;i<4;i++){assert(await frame.locator('#art'+i).evaluate(c=>c.getContext('2d').getImageData(Math.floor(c.width/2),Math.floor(c.height/2),1,1).data[3]>0));}await frame.locator('[data-art-download="0"]').click();await page.waitForTimeout(300);assert(fs.readdirSync(profile).some(n=>n.endsWith('.png')));pass('All four artwork sizes render and export through native saving');
await frame.locator('[data-tab="json"]').click();const seats=Array.from({length:12},(_,i)=>({type:'seat',x:50+i*9,y:80,zone:'VIP',seatNumber:i+1}));fs.writeFileSync(profile+'/seats.json',JSON.stringify({seats}));await frame.setInputFiles('#jsonInput',profile+'/seats.json');await frame.click('#convertJson');await frame.waitForFunction(()=>STATE.jsonOutput.includes('seatData-'));const converted=await frame.evaluate(()=>new DOMParser().parseFromString(STATE.jsonOutput,'image/svg+xml').querySelectorAll('[id^="seatData-"]').length);assert.equal(converted,12);pass('JSON-to-SVG conversion creates the expected 12 seats');
const soft=await frame.evaluate(()=>{const text=serialize();STATE.svg.querySelector('[id^="seatData-"]').id='seatData-invalid';invalidateCache();const row=runAudit(true).find(x=>x.check==='Canonical SOP ID format');parseSVG(text,true);return row;});assert.equal(soft.status,'fail');pass('Malformed IDs fail the audit rather than receiving a permissive warning');
const security=await frame.evaluate(()=>{const xml=serialize().replace('<svg ','<svg onload="window.injected=true" ').replace('</svg>','<a href="https://external.example"><rect width="1" height="1"/></a><script>window.injected=true</script><style>body{display:none}.seatTest{fill:red}</style></svg>');parseSVG(xml);const n=compareSVGNode(xml);return {rootEvent:STATE.svg.documentElement.hasAttribute('onload'),scripts:STATE.svg.querySelectorAll('script').length,external:STATE.svg.querySelectorAll('[href^="http"]').length,compareEvent:n.hasAttribute('onload'),css:[...STATE.svg.querySelectorAll('style')].every(x=>x.textContent.startsWith('svg[data-toolkit-svg=')),executed:window.injected===true};});assert.deepEqual(security,{rootEvent:false,scripts:0,external:0,compareEvent:false,css:true,executed:false});pass('Imported SVG and comparison sources remove active content and keep stylesheet rules scoped');
await page.click('#productionSend');await page.click('#dialogOK');await frame.waitForTimeout(300);assert.equal(await frame.evaluate(()=>ProductionBridge.state().seats),576);await page.click('#productionReturn');await page.click('#dialogOK');assert.equal(await page.locator('#map .seat').count(),576);assert.equal(await page.locator('#productionWorkspace').isVisible(),false);pass('Explicit production-to-canvas transfer preserves the supported seat inventory and returns to canvas');
await page.click('#productionOpen');frame=page.frames().find(f=>f.url().includes('production.html'));await frame.locator('[data-tab="workflow"]').click();await frame.click('#saveAutosaveBtn');await frame.evaluate(()=>ProductionBridge.flush());await page.click('#productionBack');await page.click('#saveProject');await page.waitForTimeout(400);const save=fs.readdirSync(profile).find(n=>n.endsWith('.venue')&&n!=='Recovery.venue');const data=JSON.parse(fs.readFileSync(profile+'/'+save,'utf8'));assert(data.production&&data.production.svg.includes('seatData-'));const helper=await page.evaluate(()=>IllustratorConversionScript);acorn.parse(helper.replace(/^#target.*\n/,''),{ecmaVersion:3});pass('Manual Illustrator conversion helper parses as ES3');
await page.waitForTimeout(1200);await page.close({runBeforeUnload:false});page=await browser.newPage({viewport:{width:1500,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.goto(info.url);await page.waitForSelector('#dialog[open]');await page.click('#dialogOK');await page.click('#productionOpen');await page.waitForFunction(()=>document.getElementById('productionFrame').contentWindow.ProductionBridge?.state().seats===576);frame=page.frames().find(f=>f.url().includes('production.html'));await frame.waitForTimeout(500);assert.equal(await frame.evaluate(()=>countSeats()),576);pass('Editor recovery restores the production working copy on the next session');
const zipBlob=await frame.evaluate(async()=>{const blob=await makeZip([{name:'Folder/map.svg',data:new TextEncoder().encode(serialize())},{name:'Folder/check.txt',data:new TextEncoder().encode('Native production ZIP')}]);return Array.from(new Uint8Array(await blob.arrayBuffer()));});const zip=await JSZip.loadAsync(Buffer.from(zipBlob),{checkCRC32:true});assert.equal(await zip.file('Folder/check.txt').async('string'),'Native production ZIP');pass('Retained production ZIP writer produces readable nested entries with valid CRC');
await frame.locator('[data-tab="workflow"]').click();await page.waitForTimeout(4500);await page.screenshot({path:base+'/tests/Production Preview.png'});assert.deepEqual(errors,[]);
}finally{if(browser)await browser.close();proc.kill();}fs.writeFileSync(base+'/tests/extra-results.json',JSON.stringify({passed:true,checks},null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
