const fs=require('fs'),path=require('path'),assert=require('assert'),{spawn}=require('child_process'),{performance}=require('perf_hooks');
const {chromium}=require('playwright');
const JSZip=require('jszip');
const sharp=require('sharp');
const base=path.resolve(__dirname,'..'),trace=require('../src/web/trace-worker'),palette=require('../src/web/trace-palette'),checks=[];function pass(s){checks.push(s);console.log('PASS '+s);}
const pixels=new Uint8ClampedArray(64*64*4);for(let y=0;y<64;y++)for(let x=0;x<64;x++)pixels.set(x<32?[240,10,10,255]:[10,10,240,255],(y*64+x)*4);
const opts={pixels:pixels.buffer,width:64,height:64,colors:2,removeWhite:false,minArea:0,tolerance:0,lockedColors:'#ff0000,#0000ff',paletteOnly:true};
const r=trace(opts);assert.deepEqual(r.paths.map(p=>p.fill).sort(),['#0000ff','#ff0000']);assert.equal(r.paths.reduce((n,p)=>n+p.contours,0),2);pass('Locked palette keeps exact brand colours and two adjacent closed regions');
assert.deepEqual(trace(opts),r);assert.throws(()=>trace({...opts,lockedColors:'#GG0000'}));assert.throws(()=>trace({...opts,lockedColors:''}));pass('Deterministic trace and invalid locked-palette rejection');
const noisy=pixels.slice();noisy.set([10,10,240,255],(10*64+10)*4);const q=palette.quantize(noisy,64,64,{colors:2,lockedColors:'#ff0000,#0000ff',paletteOnly:true,denoise:true,removeWhite:false});assert.equal(q.labels[10*64+10],q.labels[10*64+9]);pass('Optional denoising repairs an isolated colour pixel');
assert(trace({...opts,mode:'logo',curves:true}).paths.every(p=>!p.d.includes('C')));assert(trace({...opts,mode:'auto'}).paths.length===2);pass('Hard-edge mode prevents curves and automatic mode retains fixture colours');
(async()=>{const profile=base+'/tests/upgrade-'+Date.now();fs.mkdirSync(profile,{recursive:true});const proc=spawn(base+'/build/Toolkit.exe',['--self-test','--profile',profile],{windowsHide:true});let browser;try{for(let i=0;i<100&&!fs.existsSync(profile+'/server-info.json');i++)await new Promise(r=>setTimeout(r,100));const info=JSON.parse(fs.readFileSync(profile+'/server-info.json'));browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(info.url);await page.click('[data-mode="trace"]');await page.setInputFiles('#imageFile',base+'/tests/fixtures/Artwork.png');await page.waitForFunction(()=>!document.getElementById('runTrace').disabled);await page.fill('#lockedColors','#FF0000,#0000FF');await page.check('#paletteOnly');await page.click('#runTrace');await page.waitForFunction(()=>ToolkitDiagnostics.trace()!==null);const result=await page.evaluate(()=>ToolkitDiagnostics.trace());assert(result.paths.every(p=>['#ff0000','#0000ff'].includes(p.fill)));pass('Native embedded worker loads the new palette engine and controls');await page.selectOption('#traceFormat','png');await page.fill('#pngWidth','1200');await page.click('#saveTrace');for(let i=0;i<100&&!fs.existsSync(profile+'/Traced Artwork.png');i++)await page.waitForTimeout(50);const meta=await sharp(profile+'/Traced Artwork.png').metadata();assert.equal(meta.width,1200);assert.equal(meta.height,800);assert(meta.hasAlpha);pass('PNG preview saves through native host at requested size with alpha');
const folder=profile+'/Batch';fs.mkdirSync(folder);fs.copyFileSync(base+'/tests/fixtures/Artwork.png',folder+'/A.png');fs.copyFileSync(base+'/tests/fixtures/Artwork.bmp',folder+'/B.bmp');await page.selectOption('#traceFormat','svg');await page.setInputFiles('#batchFiles',folder);await page.waitForFunction(()=>document.getElementById('batchStatus').textContent.startsWith('Complete.'),{},{timeout:30000});const z=await JSZip.loadAsync(fs.readFileSync(profile+'/Traced Folder - 1.zip'),{checkCRC32:true});assert.equal(Object.keys(z.files).filter(n=>n.endsWith('.svg')).length,2);const report=JSON.parse(await z.file('Batch Report.json').async('string'));assert.equal(report.files.filter(f=>f.status==='traced').length,2);pass('Folder batch traces PNG/BMP, saves two SVGs and a per-file report in a CRC-valid ZIP');
assert.equal(errors.length,0);await page.screenshot({path:base+'/tests/Upgrade Preview.png'});pass('No uncaught browser errors in upgraded tracing workflow');fs.writeFileSync(base+'/tests/upgrade-results.json',JSON.stringify({passed:true,checks},null,2));}finally{if(browser)await browser.close();proc.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
