'use strict';
(function(root){
 const f=n=>{if(!Number.isFinite(n))throw Error('Invalid vector coordinate.');return String(Math.round(n*100000)/100000);};
 function commands(d){const tokens=d.match(/[A-Za-z]|[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?/g)||[],out=[];let i=0;while(i<tokens.length){const op=tokens[i++],count={M:2,L:2,C:6,Z:0}[op];if(count===undefined)throw Error('Unsupported trace command '+op);const values=tokens.slice(i,i+count).map(Number);if(values.length!==count||values.some(n=>!Number.isFinite(n)))throw Error('Malformed trace path.');i+=count;out.push({op,values});}return out;}
 const rgb=hex=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);
 const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 function svg(r,options={}){const mm=options.widthMM||r.width*25.4/96,h=mm*r.height/r.width;return '<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="'+f(mm)+'mm" height="'+f(h)+'mm" viewBox="0 0 '+r.width+' '+r.height+'">'+r.paths.map(p=>'<path d="'+esc(p.d)+'" fill="'+p.fill+'" fill-rule="evenodd"/>').join('')+'</svg>';}
 function eps(r,options={}){const scale=(options.widthMM||r.width*25.4/96)*72/25.4/r.width,w=r.width*scale,h=r.height*scale;let a=['%!PS-Adobe-3.0 EPSF-3.0',' %%Creator: Yousufweiji Toolkit','%%BoundingBox: 0 0 '+Math.ceil(w)+' '+Math.ceil(h),'%%HiResBoundingBox: 0 0 '+f(w)+' '+f(h),'%%LanguageLevel: 2','%%Pages: 1','%%EndComments','gsave','0 '+f(h)+' translate',f(scale)+' '+f(-scale)+' scale'];for(const p of r.paths){a.push(rgb(p.fill).map(f).join(' ')+' setrgbcolor','newpath');for(const c of commands(p.d))a.push(c.values.map(f).join(' ')+(c.values.length?' ':'')+({M:'moveto',L:'lineto',C:'curveto',Z:'closepath'}[c.op]));a.push('eofill');}a.push('grestore','showpage','%%EOF');return a.join('\n')+'\n';}
 function pdf(r,options={}){const scale=(options.widthMM||r.width*25.4/96)*72/25.4/r.width,w=r.width*scale,h=r.height*scale;let c=['q',f(scale)+' 0 0 '+f(-scale)+' 0 '+f(h)+' cm'];for(const p of r.paths){c.push(rgb(p.fill).map(f).join(' ')+' rg');for(const seg of commands(p.d))c.push(seg.values.map(f).join(' ')+(seg.values.length?' ':'')+({M:'m',L:'l',C:'c',Z:'h'}[seg.op]));c.push('f*');}c.push('Q');const stream=c.join('\n')+'\n';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 '+f(w)+' '+f(h)+'] /Resources << >> /Contents 4 0 R >>','<< /Length '+stream.length+' >>\nstream\n'+stream+'endstream'];let out='%PDF-1.4\n% Toolkit vector artwork\n',offset=[0];objects.forEach((o,i)=>{offset.push(out.length);out+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const xref=out.length;out+='xref\n0 5\n0000000000 65535 f \n'+offset.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF\n';return out;}
 function loops(d,tolerance=.15){const result=[];let pts=[],current=[0,0];const distance=(p,a,b)=>{const dx=b[0]-a[0],dy=b[1]-a[1],l=dx*dx+dy*dy,t=l?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/l)):0;return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);};const mid=(a,b)=>[(a[0]+b[0])/2,(a[1]+b[1])/2];function flat(a,b,c,d,depth=0){if(depth>12||Math.max(distance(b,a,d),distance(c,a,d))<=tolerance){pts.push(d);return;}const ab=mid(a,b),bc=mid(b,c),cd=mid(c,d),abc=mid(ab,bc),bcd=mid(bc,cd),center=mid(abc,bcd);flat(a,ab,abc,center,depth+1);flat(center,bcd,cd,d,depth+1);}
 for(const s of commands(d)){if(s.op==='M'){if(pts.length)result.push(pts);pts=[s.values];current=s.values;}else if(s.op==='L'){pts.push(s.values);current=s.values;}else if(s.op==='C'){const v=s.values;flat(current,v.slice(0,2),v.slice(2,4),v.slice(4,6));current=v.slice(4,6);}else if(s.op==='Z'){if(pts.length>2)result.push(pts);pts=[];}}if(pts.length>2)result.push(pts);return result;}
 function dxf(r,options={}){const scale=(options.widthMM||r.width*25.4/96)/r.width,pairs=[];const add=(code,value)=>pairs.push(String(code),String(value));add(0,'SECTION');add(2,'HEADER');add(9,'$ACADVER');add(1,'AC1018');add(9,'$INSUNITS');add(70,4);add(0,'ENDSEC');add(0,'SECTION');add(2,'TABLES');add(0,'TABLE');add(2,'LAYER');add(70,r.paths.length);r.paths.forEach((p,i)=>{add(0,'LAYER');add(100,'AcDbSymbolTableRecord');add(100,'AcDbLayerTableRecord');add(2,'COLOR_'+(i+1));add(70,0);add(62,i%7+1);add(420,parseInt(p.fill.slice(1),16));add(6,'CONTINUOUS');});add(0,'ENDTAB');add(0,'ENDSEC');add(0,'SECTION');add(2,'ENTITIES');r.paths.forEach((p,i)=>{for(const pts of loops(p.d)){add(0,'LWPOLYLINE');add(100,'AcDbEntity');add(8,'COLOR_'+(i+1));add(420,parseInt(p.fill.slice(1),16));add(100,'AcDbPolyline');add(90,pts.length);add(70,1);for(const [x,y] of pts){add(10,f(x*scale));add(20,f((r.height-y)*scale));}}});add(0,'ENDSEC');add(0,'EOF');return pairs.join('\r\n')+'\r\n';}
 root.VectorExport={svg,eps,pdf,dxf,commands,loops};
})(typeof window==='undefined'?globalThis:window);
