using System;
using System.IO;
using System.Text;
using System.Net;
using System.Net.Sockets;
using System.Threading;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Web.Script.Serialization;
using System.IO.Compression;
using System.Reflection;
[assembly: AssemblyTitle("VenueForge Pro")]
[assembly: AssemblyProduct("VenueForge Pro Desktop")]
[assembly: AssemblyVersion("3.0.0.0")]
[assembly: AssemblyFileVersion("3.0.0.0")]
class Desktop : ApplicationContext {
 readonly string root,profile,token=Guid.NewGuid().ToString("N");
 readonly CepManager cepManager; readonly bool testing; readonly Control ui=new Control();
 TcpListener server; NotifyIcon tray; System.Windows.Forms.Timer timer;
 DateTime seen=DateTime.UtcNow; int port,dialogs; volatile bool closed;
 readonly object recoveryLock=new object();
 readonly JavaScriptSerializer json=new JavaScriptSerializer { MaxJsonLength=60000000, RecursionLimit=150 };
 string Origin {get{return "http://127.0.0.1:"+port;}}
 string Url {get{return Origin+"/"+token+"/index.html";}}
 static string EdgePath(){foreach(string parent in new[]{Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)}){string p=Path.Combine(parent,"Microsoft","Edge","Application","msedge.exe");if(File.Exists(p))return p;}throw new Exception("Microsoft Edge is required to display this app. Install Microsoft Edge, then reopen Toolkit.");}
 [STAThread] static void Main(string[] args){AppContext.SetSwitch("Switch.System.IO.UseLegacyPathHandling",false);AppContext.SetSwitch("Switch.System.IO.BlockLongPaths",false);if(args.Length==4&&args[0]=="--export-ai"){try{NativeFormats.SaveAI(File.ReadAllText(args[1],Encoding.UTF8),args[2],Path.GetDirectoryName(args[1]));File.WriteAllText(args[3],"OK");}catch(Exception e){File.WriteAllText(args[3],e.Message);}return;}if(Array.IndexOf(args,"--native-surface")>=0){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);string input=null;int ni=Array.IndexOf(args,"--native-file");if(ni>=0&&ni+1<args.Length)input=Path.GetFullPath(args[ni+1]);try{NativeDocument doc;if(input!=null&&File.Exists(input)){string text=File.ReadAllText(input,Encoding.UTF8);string extension=Path.GetExtension(input);doc=extension.Equals(".venue",StringComparison.OrdinalIgnoreCase)?NativeSceneGraph.FromVenue(text):extension.Equals(".svg",StringComparison.OrdinalIgnoreCase)?NativeSceneGraph.FromSvg(text):NativeSceneGraph.Deserialize(text);}else doc=NativeSceneGraph.NewDocument(1200,800);string output=input!=null&&Path.GetExtension(input).Equals(".native.json",StringComparison.OrdinalIgnoreCase)?input:Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"Toolkit Native Document.native.json");Application.Run(new NativeCanvasForm(doc,output));}catch(Exception e){MessageBox.Show(e.Message,"Native surface could not start",MessageBoxButtons.OK,MessageBoxIcon.Error);}return;}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);bool test=Array.IndexOf(args,"--self-test")>=0;string profile=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"VenueForgePro");int pi=Array.IndexOf(args,"--profile");if(pi>=0&&pi+1<args.Length)profile=Path.GetFullPath(args[pi+1]);bool created;using(Mutex mutex=new Mutex(true,"Local\\VenueForgePro-"+(test?Guid.NewGuid().ToString("N"):"Desktop"),out created)){if(!created){try{string existing=File.ReadAllText(Path.Combine(profile,"Session.url"));Uri u=new Uri(existing);if(u.Scheme!="http"||u.Host!="127.0.0.1"||!System.Text.RegularExpressions.Regex.IsMatch(u.AbsolutePath,@"^/[a-f0-9]{32}/index\.html$"))throw new Exception();Process.Start(new ProcessStartInfo(EdgePath(),"--user-data-dir=\""+Path.Combine(profile,"Browser")+"\" --app=\""+existing+"\""){UseShellExecute=false,CreateNoWindow=true});}catch{MessageBox.Show("Toolkit is already running. Look for its window or its icon in the system tray.","VenueForge Pro");}return;}try{Application.Run(new Desktop(profile,test));}catch(Exception e){if(test){Directory.CreateDirectory(profile);File.WriteAllText(Path.Combine(profile,"startup-error.txt"),e.ToString());}else MessageBox.Show(e.Message,"Toolkit could not start",MessageBoxButtons.OK,MessageBoxIcon.Error);}}}
 Desktop(string data,bool test){profile=data;testing=test;CepManager.VerifyEmbeddedSetup();cepManager=new CepManager(profile,test);Directory.CreateDirectory(profile);root=Path.Combine(profile,"App","3.0.0");Directory.CreateDirectory(root);foreach(string resource in Assembly.GetExecutingAssembly().GetManifestResourceNames()){if(!resource.StartsWith("web."))continue;string asset=resource.Substring(4);ExtractAsset(asset);}ui.CreateControl();var handle=ui.Handle;
 server=new TcpListener(IPAddress.Loopback,0);server.Start(20);port=((IPEndPoint)server.LocalEndpoint).Port;Atomic(Path.Combine(profile,"Session.url"),Encoding.UTF8.GetBytes(Url));ThreadPool.QueueUserWorkItem(Accept);
 if(testing)File.WriteAllText(Path.Combine(profile,"server-info.json"),"{\"url\":\""+Url+"\",\"token\":\""+token+"\"}");
 if(!testing) {string edge=EdgePath();Process.Start(new ProcessStartInfo(edge,"--user-data-dir=\""+Path.Combine(profile,"Browser")+"\" --app=\""+Url+"\" --no-first-run --disable-extensions --disable-background-mode --window-size=1440,980"){UseShellExecute=false,CreateNoWindow=true});tray=new NotifyIcon{Icon=SystemIcons.Application,Text="VenueForge Pro",Visible=true};var menu=new ContextMenuStrip();menu.Items.Add("Open Toolkit",null,(s,e)=>Process.Start(new ProcessStartInfo(edge,"--user-data-dir=\""+Path.Combine(profile,"Browser")+"\" --app=\""+Url+"\""){UseShellExecute=false,CreateNoWindow=true}));menu.Items.Add("Exit Toolkit",null,(s,e)=>{if(MessageBox.Show("Save your project before exiting. Close the Toolkit service?","Exit Toolkit",MessageBoxButtons.YesNo)==DialogResult.Yes)ExitThread();});tray.ContextMenuStrip=menu;}
 timer=new System.Windows.Forms.Timer{Interval=10000};timer.Tick+=(s,e)=>{if(dialogs==0&&(DateTime.UtcNow-seen).TotalSeconds>(testing?300:150))ExitThread();};timer.Start();
 }
 void ExtractAsset(string asset){using(Stream source=Assembly.GetExecutingAssembly().GetManifestResourceStream("web."+asset)){if(source==null)throw new Exception("The app is incomplete. Download Toolkit.exe again.");using(var content=new MemoryStream()){source.CopyTo(content);Atomic(Path.Combine(root,asset),content.ToArray());}}}
 void Accept(object state){while(!closed){try{TcpClient c=server.AcceptTcpClient();ThreadPool.QueueUserWorkItem(o=>Handle((TcpClient)o),c);}catch{if(closed)return;}}}
 static string Line(Stream s,int max){var b=new List<byte>();while(b.Count<max){int c=s.ReadByte();if(c<0)throw new IOException("Incomplete request");if(c==10)return Encoding.ASCII.GetString(b.ToArray()).TrimEnd('\r');b.Add((byte)c);}throw new IOException("Request header too long");}
 void Reply(Stream s,int code,byte[] bytes,string type){string head="HTTP/1.1 "+code+" "+(code==200?"OK":"Error")+"\r\nContent-Type: "+type+"\r\nContent-Length: "+bytes.Length+"\r\nConnection: close\r\nCache-Control: no-store\r\nX-Content-Type-Options: nosniff\r\nReferrer-Policy: no-referrer\r\nCross-Origin-Resource-Policy: same-origin\r\n\r\n";byte[] h=Encoding.ASCII.GetBytes(head);s.Write(h,0,h.Length);s.Write(bytes,0,bytes.Length);}
 void Json(Stream s,int code,object obj){string t;lock(json)t=json.Serialize(obj);Reply(s,code,Encoding.UTF8.GetBytes(t),"application/json; charset=utf-8");}
 void Handle(TcpClient client){using(client){client.ReceiveTimeout=15000;client.SendTimeout=15000;using(NetworkStream s=client.GetStream()){try{
 string[] request=Line(s,4096).Split(' ');if(request.Length!=3){Json(s,400,new{error="Invalid request"});return;}var headers=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);int size=0;while(true){string h=Line(s,8192);size+=h.Length;if(size>32768)throw new IOException("Headers too large");if(h.Length==0)break;int colon=h.IndexOf(':');if(colon<1)throw new IOException("Invalid header");string k=h.Substring(0,colon);if(headers.ContainsKey(k))throw new IOException("Duplicate header");headers[k]=h.Substring(colon+1).Trim();}
 string host,origin;if(!headers.TryGetValue("Host",out host)||host!="127.0.0.1:"+port||(headers.TryGetValue("Origin",out origin)&&origin!=Origin)){Json(s,403,new{error="Origin not allowed"});return;}
 string prefix="/"+token+"/";string target=request[1].Split('?')[0];if(!target.StartsWith(prefix,StringComparison.Ordinal)){Json(s,403,new{error="Session not allowed"});return;}target=target.Substring(prefix.Length);
 if(request[0]=="GET"&&!target.StartsWith("api/")){var allowed=new Dictionary<string,string>();foreach(string r in Assembly.GetExecutingAssembly().GetManifestResourceNames()){if(!r.StartsWith("web."))continue;string asset=r.Substring(4),ext=Path.GetExtension(asset);allowed[asset]=ext==".html"?"text/html; charset=utf-8":ext==".css"?"text/css; charset=utf-8":"text/javascript; charset=utf-8";};if(!allowed.ContainsKey(target)){Json(s,404,new{error="Not found"});return;}Reply(s,200,File.ReadAllBytes(Path.Combine(root,target)),allowed[target]);return;}
 string auth;if(!headers.TryGetValue("X-Toolkit-Session",out auth)||auth!=token){Json(s,403,new{error="Session header required"});return;}
 seen=DateTime.UtcNow;
 if(request[0]=="GET"&&target=="api/cep"){Json(s,200,cepManager.Status());return;}
 if(request[0]=="GET"&&target=="api/workspace"){string f=Path.Combine(profile,"Workspace.json");Json(s,200,new{content=File.Exists(f)?File.ReadAllText(f):null});return;}
 if(request[0]=="GET"&&target=="api/heartbeat"){Json(s,200,new{ok=true});return;}
 if(request[0]=="GET"&&(target=="api/recovery"||target=="api/studio")){string content=null;lock(recoveryLock){string f=Path.Combine(profile,target=="api/studio"?"Production.json":"Recovery.venue");if(File.Exists(f))content=File.ReadAllText(f,Encoding.UTF8);}Json(s,200,new{content=content});return;}
 if(request[0]!="POST"||!(target=="api/save"||target=="api/recovery"||target=="api/studio"||target=="api/decode"||target=="api/xlsx"||target=="api/cep"||target=="api/workspace")){Json(s,404,new{error="Route not found"});return;}
 string length,type;int n;if(headers.ContainsKey("Transfer-Encoding")||!headers.TryGetValue("Content-Length",out length)||!int.TryParse(length,out n)||n<0||n>55000000||!headers.TryGetValue("Content-Type",out type)||!type.StartsWith("application/json")){Json(s,400,new{error="Invalid request body"});return;}
 byte[] bytes=new byte[n];for(int offset=0;offset<n;){int got=s.Read(bytes,offset,n-offset);if(got==0)throw new IOException("Incomplete body");offset+=got;}Dictionary<string,object> body;lock(json)body=json.Deserialize<Dictionary<string,object>>(Encoding.UTF8.GetString(bytes));if(body==null)throw new Exception("Missing body");
 if(target=="api/workspace"){Atomic(Path.Combine(profile,"Workspace.json"),Encoding.UTF8.GetBytes(Text(body,"content",100000)));Json(s,200,new{ok=true});return;}
 if(target=="api/cep"){Interlocked.Increment(ref dialogs);try{object value;bool debug=body.TryGetValue("debug",out value)&&value is bool&&(bool)value;string backup=body.TryGetValue("backup",out value)&&value is string?(string)value:null;Json(s,200,cepManager.Apply(Text(body,"action",20),debug,backup));}finally{Interlocked.Decrement(ref dialogs);}return;}
 if(target=="api/decode"){Json(s,200,NativeFormats.Decode(Text(body,"content",45000000)));return;}
 if(target=="api/xlsx"){Json(s,200,NativeFormats.ReadWorkbook(Text(body,"content",35000000)));return;}

 if(target=="api/recovery"||target=="api/studio"){string content=Text(body,"content",50000000);lock(recoveryLock)Atomic(Path.Combine(profile,target=="api/studio"?"Production.json":"Recovery.venue"),Encoding.UTF8.GetBytes(content));Json(s,200,new{ok=true});return;}
 string kind=Text(body,"kind",20),name=Text(body,"name",180);var extensions=new Dictionary<string,string>{{"project",".venue"},{"svg",".svg"},{"csv",".csv"},{"report",".txt"},{"package",".zip"},{"archive",".zip"},{"pdf",".pdf"},{"eps",".eps"},{"dxf",".dxf"},{"ai",".ai"},{"png",".png"},{"jpg",".jpg"},{"jpeg",".jpeg"},{"webp",".webp"},{"gif",".gif"},{"bmp",".bmp"},{"tif",".tif"},{"tiff",".tiff"},{"json",".json"},{"xml",".xml"},{"tsv",".tsv"},{"jsx",".jsx"}};if(!extensions.ContainsKey(kind))throw new Exception("Unsupported file kind");name=Path.GetFileName(name);foreach(char c in Path.GetInvalidFileNameChars())name=name.Replace(c,'_');name=Path.GetFileNameWithoutExtension(name)+extensions[kind];byte[] output;
 if(kind=="package"){object entries;if(!body.TryGetValue("entries",out entries)||!(entries is System.Collections.ArrayList))throw new Exception("Missing package files");var list=(System.Collections.ArrayList)entries;if(list.Count<1||list.Count>10)throw new Exception("Invalid package size");using(var ms=new MemoryStream()){using(var archive=new ZipArchive(ms,ZipArchiveMode.Create,true)){var names=new HashSet<string>();foreach(object obj in list){var entry=obj as Dictionary<string,object>;if(entry==null)throw new Exception("Invalid package entry");string en=Text(entry,"name",100);if(en!=Path.GetFileName(en)||en.Contains("..")||!names.Add(en))throw new Exception("Invalid package filename");var ze=archive.CreateEntry(en,CompressionLevel.Optimal);using(var writer=new StreamWriter(ze.Open(),new UTF8Encoding(false)))writer.Write(Text(entry,"content",50000000));}}output=ms.ToArray();}}
 else output=body.ContainsKey("encoding")&&Convert.ToString(body["encoding"])=="base64"?Convert.FromBase64String(Text(body,"content",50000000)):Encoding.UTF8.GetBytes(Text(body,"content",50000000));
 string destination=null;Interlocked.Increment(ref dialogs);try{if(testing){destination=Path.Combine(profile,name);}else ui.Invoke((Action)(()=>{using(var dialog=new SaveFileDialog{FileName=name,DefaultExt=extensions[kind],Filter=kind.ToUpperInvariant()+" file|*"+extensions[kind],AddExtension=true,OverwritePrompt=true,RestoreDirectory=true}){if(dialog.ShowDialog()==DialogResult.OK)destination=dialog.FileName;}}));if(destination!=null){if(kind=="ai"){if(testing)throw new Exception("Native AI export requires an interactive Illustrator session; not exercised in test mode.");ExportAIWithTimeout(Encoding.UTF8.GetString(output),destination);}else Atomic(destination,output);}}finally{Interlocked.Decrement(ref dialogs);}
 Json(s,200,new{cancelled=destination==null,name=destination==null?null:Path.GetFileName(destination)});
 }catch(Exception e){try{Json(s,400,new{error=e.Message});}catch{}}}}}
 void ExportAIWithTimeout(string svg,string destination){string stem=Path.Combine(profile,"AIJob-"+Guid.NewGuid().ToString("N")),input=stem+".svg",result=stem+".txt";try{File.WriteAllText(input,svg,new UTF8Encoding(false));string arguments="--export-ai \""+input+"\" \""+destination+"\" \""+result+"\"";using(var helper=Process.Start(new ProcessStartInfo(Assembly.GetExecutingAssembly().Location,arguments){UseShellExecute=false,CreateNoWindow=true})){if(!helper.WaitForExit(60000)){try{helper.Kill();}catch{}throw new Exception("Illustrator did not respond within 60 seconds. Open Illustrator and retry, or use SVG/EPS and the Illustrator conversion script.");}string status=File.Exists(result)?File.ReadAllText(result):"Illustrator export helper did not return a result.";if(status!="OK")throw new Exception(status);}}finally{if(File.Exists(input))File.Delete(input);if(File.Exists(result))File.Delete(result);}}
 static string Text(Dictionary<string,object> body,string key,int limit){object v;if(!body.TryGetValue(key,out v)||!(v is string)||((string)v).Length>limit)throw new Exception("Invalid "+key);return (string)v;}
 static void Atomic(string destination,byte[] bytes){string temp=destination+"."+Guid.NewGuid().ToString("N")+".tmp";try{using(var file=new FileStream(temp,FileMode.CreateNew,FileAccess.Write,FileShare.None,4096,FileOptions.WriteThrough)){file.Write(bytes,0,bytes.Length);file.Flush(true);}if(File.Exists(destination))File.Replace(temp,destination,null);else File.Move(temp,destination);}finally{if(File.Exists(temp))File.Delete(temp);}}
 protected override void ExitThreadCore(){closed=true;if(server!=null)server.Stop();if(timer!=null)timer.Dispose();if(tray!=null)tray.Dispose();ui.Dispose();base.ExitThreadCore();}
}
