using System;
using System.IO;
using System.IO.Compression;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Drawing2D;
using System.Text;
using System.Xml;
using System.Collections.Generic;
using System.Runtime.InteropServices;
class NativeFormats {
 public static object Decode(string data){byte[] bytes=Convert.FromBase64String(data);if(bytes.Length>30000000)throw new Exception("Image exceeds 30 MB.");using(var stream=new MemoryStream(bytes))using(var image=Image.FromStream(stream,true,true)){if((long)image.Width*image.Height>60000000)throw new Exception("Image exceeds 60 megapixels.");int frames=1;foreach(Guid id in image.FrameDimensionsList){frames=Math.Max(frames,image.GetFrameCount(new FrameDimension(id)));}double scale=Math.Min(1,2048.0/Math.Max(image.Width,image.Height));using(var bitmap=new Bitmap(Math.Max(1,(int)Math.Round(image.Width*scale)),Math.Max(1,(int)Math.Round(image.Height*scale)),PixelFormat.Format32bppArgb)){using(var g=Graphics.FromImage(bitmap)){g.Clear(Color.Transparent);g.InterpolationMode=InterpolationMode.HighQualityBicubic;g.CompositingMode=CompositingMode.SourceCopy;g.DrawImage(image,0,0,bitmap.Width,bitmap.Height);}using(var output=new MemoryStream()){bitmap.Save(output,ImageFormat.Png);return new{data=Convert.ToBase64String(output.ToArray()),width=image.Width,height=image.Height,frames=frames,decodedWidth=bitmap.Width,decodedHeight=bitmap.Height};}}}}
 static XmlDocument Xml(ZipArchiveEntry entry){if(entry==null)throw new Exception("The workbook is missing a required XML part.");if(entry.Length>60000000)throw new Exception("Workbook XML is too large.");var doc=new XmlDocument{XmlResolver=null};using(var s=entry.Open())using(var reader=XmlReader.Create(s,new XmlReaderSettings{DtdProcessing=DtdProcessing.Prohibit,XmlResolver=null,MaxCharactersInDocument=60000000}))doc.Load(reader);return doc;}
 public static object ReadWorkbook(string data){var bytes=Convert.FromBase64String(data);if(bytes.Length>25000000)throw new Exception("Workbook exceeds 25 MB.");using(var ms=new MemoryStream(bytes))using(var zip=new ZipArchive(ms,ZipArchiveMode.Read)){if(zip.Entries.Count>3000)throw new Exception("Workbook has too many parts.");long total=0;foreach(var e in zip.Entries){total+=e.Length;if(total>100000000)throw new Exception("Expanded workbook exceeds 100 MB.");}
 var workbook=Xml(zip.GetEntry("xl/workbook.xml"));var first=workbook.SelectSingleNode("//*[local-name()='sheets']/*[local-name()='sheet']") as XmlElement;if(first==null)throw new Exception("Workbook has no worksheets.");string relation=first.GetAttribute("id","http://schemas.openxmlformats.org/officeDocument/2006/relationships"),target=null;var rels=Xml(zip.GetEntry("xl/_rels/workbook.xml.rels"));foreach(XmlElement r in rels.DocumentElement.ChildNodes){if(r.GetAttribute("Id")==relation){if(r.GetAttribute("TargetMode")=="External")throw new Exception("External worksheet references are unsupported.");target=r.GetAttribute("Target");break;}}if(target==null||target.Contains("..")||target.Contains("\\")||target.Contains(":"))throw new Exception("Invalid worksheet relationship.");target=target.StartsWith("/")?target.TrimStart('/'):(target.StartsWith("xl/")?target:"xl/"+target);
 var shared=new List<string>();var strings=zip.GetEntry("xl/sharedStrings.xml");if(strings!=null){var sd=Xml(strings);foreach(XmlNode item in sd.SelectNodes("//*[local-name()='si']")){var value=new StringBuilder();foreach(XmlNode t in item.SelectNodes(".//*[local-name()='t']"))value.Append(t.InnerText);shared.Add(value.ToString());}}
 var sheet=Xml(zip.GetEntry(target));var lines=new List<string>();foreach(XmlNode row in sheet.SelectNodes("//*[local-name()='sheetData']/*[local-name()='row']")){if(lines.Count>50000)throw new Exception("Manifest exceeds 50,000 rows.");var values=new List<string>();foreach(XmlElement cell in row.SelectNodes("*[local-name()='c']")){int col=0;foreach(char c in cell.GetAttribute("r")){if(c<'A'||c>'Z')break;col=col*26+c-'A'+1;}if(col<1)col=values.Count+1;if(col>1000)throw new Exception("Worksheet exceeds the supported manifest width.");while(values.Count<col)values.Add("");string value="";if(cell.GetAttribute("t")=="inlineStr"){foreach(XmlNode t in cell.SelectNodes(".//*[local-name()='t']"))value+=t.InnerText;}else{var v=cell.SelectSingleNode("*[local-name()='v']");value=v==null?"":v.InnerText;if(cell.GetAttribute("t")=="s"){int index;if(!int.TryParse(value,out index)||index<0||index>=shared.Count)throw new Exception("Invalid shared string reference.");value=shared[index];}}values[col-1]="\""+value.Replace("\"","\"\"")+"\"";}lines.Add(String.Join(",",values.ToArray()));}
 return new{csv=String.Join("\r\n",lines.ToArray()),sheet=first.GetAttribute("name"),rows=lines.Count};}}
 static string Quote(string s){return "\""+s.Replace("\\","\\\\").Replace("\"","\\\"").Replace("\r","\\r").Replace("\n","\\n")+"\"";}
 public static void SaveAI(string svg,string destination,string profile){if(svg.IndexOf("<!DOCTYPE",StringComparison.OrdinalIgnoreCase)>=0||svg.IndexOf("<!ENTITY",StringComparison.OrdinalIgnoreCase)>=0||svg.IndexOf("<script",StringComparison.OrdinalIgnoreCase)>=0||svg.IndexOf("href",StringComparison.OrdinalIgnoreCase)>=0)throw new Exception("AI export accepts generated vector artwork only.");Type type=Type.GetTypeFromProgID("Illustrator.Application");if(type==null)throw new Exception("Native AI export needs Adobe Illustrator installed. Use PDF, EPS or SVG for standalone export.");string input=Path.Combine(profile,"AI-"+Guid.NewGuid().ToString("N")+".svg"),output=Path.Combine(Path.GetDirectoryName(destination),"Toolkit-"+Guid.NewGuid().ToString("N")+".ai");object app=null;
 try{File.WriteAllText(input,svg,new UTF8Encoding(false));try{app=Marshal.GetActiveObject("Illustrator.Application");}catch{app=Activator.CreateInstance(type);}dynamic illustrator=app;string script="(function(){var d=null;try{d=app.open(new File("+Quote(input)+"));var o=new IllustratorSaveOptions();o.pdfCompatible=true;d.saveAs(new File("+Quote(output)+"),o);d.close(SaveOptions.DONOTSAVECHANGES);return 'TOOLKIT_OK';}catch(e){if(d){try{d.close(SaveOptions.DONOTSAVECHANGES);}catch(x){}}return 'TOOLKIT_ERROR: '+e;}})();";string result=Convert.ToString(illustrator.DoJavaScript(script));if(result!="TOOLKIT_OK"||!File.Exists(output))throw new Exception(result??"Illustrator did not create an AI file.");if(File.Exists(destination))File.Replace(output,destination,null);else File.Move(output,destination);}
 finally{if(app!=null&&Marshal.IsComObject(app))Marshal.ReleaseComObject(app);if(File.Exists(input))File.Delete(input);if(File.Exists(output))File.Delete(output);}}
}
